// The array of quotes
module.exports = [
  {
    id: "0",
    quote:
      "Si vous n’aimez pas la mer… Si vous n’aimez pas la montagne… Si vous n’aimez pas la ville… Allez vous faire foutre !",
    personage: "Michel Poicard",
    actor: "Jean-Paul Belmondo",
    film: "A bout de souffle",
    year: 1959,
    from: "Jean-Luc Godard",
  },
  {
    id: "1",
    quote:
      " -Vous voulez un whisky? -Oui juste un doigt. -Vous voulez pas un whisky d'abord ?",
    personage: ["Commissaire Bialès", "Odile Deray"],
    actor: ["Gérard Darmon", "Chantal Laubay"],
    film: "La cité de la peur",
    year: 1994,
    from: "Alain Berbérian",
  },
  {
    id: "2",
    quote:
      " - Faut pas faire attention, Théo est une brute née de la guerre. -En langage clinique, on appelle ça un paranoïaque, en langage militaire un brigadier. ",
    personage: ["Gensac", "Goldman"],
    actor: ["Maurice Biraud", "Charles Aznavour"],
    film: "Un taxi pour Tobrouk",
    year: 1961,
    from: "Denys de La Patellière",
  },
  {
    id: "3",
    quote:
      "- Ça sent la fraude fiscale ! -A quoi tu sens ça ? -A l’épaisseur de la moquette.",
    personage: ["Bob", "Antoine"],
    actor: ["Gérard Depardieu", "Michel Blanc"],
    film: "Tenue de soirée",
    year: 1985,
    from: " Bertrand Blier",
  },
  {
    id: "4",
    quote:
      "- J’ai bon caractère mais j’ai le glaive vengeur et le bras séculier. L’aigle va fondre sur la vieille buse.- C’est chouette ça, comme métaphore… - C’est pas une métaphore, c’est une périphrase. - Fais pas chier ! - Ca c’est une métaphore.",
    personage: ["Monsieur Charles", "2 hommes de main"],
    actor: ["Bernard Blier", "Jean Saudray", "Dominique Zardi"],
    film: " Faut pas prendre les enfants du bon dieu pour des canards sauvages",
    year: 1968,
    from: "Michel Audiard",
  },
  {
    id: "5",
    quote:
      "Avoir l'air d'un faux-jeton à ce point-là, j'te jure que c'est vraiment de la franchise !",
    personage: "Pépé le moko",
    actor: "Jean Gabin",
    film: "Pépé le moko",
    year: 1939,
    from: "Julien Duvivier",
  },
  {
    id: "6",
    quote: "Les vieux, faudrait les tuer dés la naissance !",
    personage: "Dédé",
    actor: "Jean-Pierre Daroussin",
    film: "Marius et Jeannette",
    year: 1997,
    from: " Robert Guédiguian",
  },
  {
    id: "7",
    quote:
      "J’adore ces ambiances d’ANPE, c’est convivial, c’est chaleureux, et puis c’est agréable d’être humilié de temps en temps",
    personage: "Jean-Jacques Castella",
    actor: "Jean-Pierre Bacri",
    film: "Le goût des autres",
    year: 2000,
    from: "Agnès Jaoui",
  },
  {
    id: "8",
    quote:
      "Cocu est un mot pour les riches. Moi, si ça m’arrivait, je ne serais pas cocu, je serais malheureux.",
    personage: "Aimable Castanier",
    actor: "Raimu",
    film: "La femme du Boulanger",
    year: 1934,
    from: "Marcel Pagnol",
  },
  {
    id: "9",
    quote:
      "- En tout cas, ils peuvent me tuer je ne parlerai pas - Mais moi non plus ! ils peuvent vous tuer, je ne parlerai pas - Je savais qu’on pouvait compter sur vous",
    personage: ["Augustin Bouvet", "Stanislas Lefort"],
    actor: ["Bourvil", "Louis de Funès"],
    film: "La grande vadrouille",
    year: 1966,
    from: "Gérard Oury",
  },
  {
    id: "10",
    quote:
      "J’ai vécu avec une femme, et puis, au bout de 48 heures, elle a décidé qu’on se séparerait d’un commun accord. Alors j’ai pas bien supporté. J’ai même essayé de me suicider [...] J’ai mis l’adagio d’Albinoni, j’ai avalé deux tubes de laxatifs et puis hop ! j’ai perdu 16 kilos et ma moquette.",
    personage: "Jean-Claude Dusse",
    actor: "Michel Blanc",
    film: "Les Bronzés",
    year: 1978,
    from: "Patrice Leconte",
  },
  {
    id: "11",
    quote:
      "On ne peut pas faire l’amour du matin au soir. C’est pour ça qu’on a inventé le travail.",
    personage: "Dr Bicard",
    actor: "Jean Dasté",
    film: "L’Homme qui aimait les femmes",
    year: 1977,
    from: "François Truffaut",
  },
  {
    id: "12",
    quote:
      "Vous au moins vous ne risquez pas d'être un légume puisque même un artichaut a du cœur !",
    personage: "Amélie",
    actor: "Audrey Tautou",
    film: "Le fabuleux destin d'Amélie Poulain",
    year: 2001,
    from: "Jean-Pierre Jeunet",
  },
  {
    id: "13",
    quote:
      "Avec un peu de chic, elle serait pas mal. C'est comme mon hareng, avec un peu de sauce, il serait pas mal..",
    personage: "Gabriel Marcassus",
    actor: "Philippe Noiret",
    film: "La Vieille fille",
    year: 1972,
    from: "Jean-Pierre Blanc",
  },
  {
    id: "14",
    quote:
      "- Il faut mettre un timbre si tu veux que le courrier parte. - Il est hors de question que je lèche le cul de la république.",
    personage: ["Le facteur", "Jo "],
    actor: ["Bernie Bonvoisin", "Victor Lanoux"],
    film: "Les démons de Jésus",
    year: 197,
    from: "Bernie Bonvoisin",
  },
  {
    id: "15",
    quote:
      "Vous êtes riche et vous voudriez être aimé comme un pauvre. Et les pauvres on ne peut quand même pas tout leur prendre aux pauvres ",
    personage: "Garance",
    actor: "Arlety",
    film: "Le sang d’un poete",
    year: 1945,
    from: "Marcel Carné",
  },
  {
    id: "16",
    quote:
      "Quelque fois dans la rue, il y a devant moi une belle fille qui marche les cheveux au vent. Les battements de mon cœur s'accélèrent, je presse le pas pour arriver à sa hauteur. Je la regarde, elle est moche. Et bien je vous assure, je suis soulagé. Je trouve ça rassurant",
    personage: "Fergus ",
    actor: "Charles Denner",
    film: "La mariée était en noir",
    year: 1968,
    from: "François Truffaut",
  },
  {
    id: "17",
    quote:
      "Si l'on peut se payer mon corps en y mettant le prix, je n'aime pas beaucoup qu'on se paye ma tête !",
    personage: "Isabella ",
    actor: "Ginette Leclerc",
    film: "Compartiment de dames seules",
    year: 1934,
    from: "Christian-Jacque",
  },
  {
    id: "18",
    quote:
      "- Et toi, tu penses quoi de la peine de mort ? - Des fois je suis contre mais des fois je ne suis pas pour !",
    personage: ["Mademoiselle Lajoie", "Gérard Barbier"],
    actor: ["Josiane Balasko", "Coluche"],
    film: "Le maître d’école",
    year: 1981,
    from: "Claude Berri",
  },
  {
    id: "19",
    quote:
      "Y paraît que celui qui a inventé la bombe atomique, il aimait vachement les gens ! Alors arrête de me rendre service, tu veux !",
    personage: ["Daniel", "Guy"],
    actor: ["Bernard Giraudeau", "Michel Blanc"],
    film: "Viens chez moi j’habite chez une copine",
    year: 1981,
    from: "Patrice Leconte",
  },
  {
    id: "20",
    quote:
      "Travaille, toi. Hein, t'es pas comme Napoléon, toi, t'es pas capable de parler et de faire le ménage en même temps ? - Il faisait le ménage, Napoléon ?",
    personage: ["Henri", "Denis"],
    actor: ["Jean-Pierre Bacri", "Jean-Pierre Darroussin"],
    film: "Un air de famille ",
    year: 1996,
    from: "Cédric Klapish",
  },
  {
    id: "21",
    quote: "Pas d'bras, pas d'chocolat!",
    personage: "Driss",
    actor: "Omar Sy",
    film: "Intouchables",
    year: 2011,
    from: "Olivier Nakache et Éric Toledano",
  },
  {
    id: "22",
    quote:
      "Écoute Bernard… J’crois que toi et moi, on a un peu le même problème ; c’est qu’on peut pas vraiment tout miser sur notre physique, surtout toi. Alors si je peux me permettre de te donner un conseil, c’est oublie qu’t’as aucune chance, vas-y, fonce ! On sait jamais, sur un malentendu ça peut marcher…",
    personage: "Jean-Claude Dusse",
    actor: "Michel Blanc",
    film: "Les Bronzés font du ski",
    year: 1979,
    from: "Patrice Leconte",
  },
  {
    id: "23",
    quote:
      "Quand te reverrais-je ? Pays merveilleux ! Où ceux qui s’aiment, vivent à deux !",
    personage: "Jean-Claude Dusse",
    actor: "Michel Blanc",
    film: "Les Bronzés font du ski",
    year: 1979,
    from: "Patrice Leconte",
  },

  {
    id: "24",
    quote: "Odile Deray ?- Non! Non! Je suis le pape et j’attends ma sœur.",
    personage: ["Serge Karamazov", "Odile Deray"],
    actor: ["Alain Chabat", "Chantal Laubay"],
    film: "La cité de la peur",
    year: 1994,
    from: "Alain Berbérian",
  },
  {
    id: "25",
    quote:
      "- Il s’appelle Juste Leblanc. – Ah bon, il n’a pas de prénom? – Je viens de vous le dire Juste Leblanc… Votre prénom c’est François, c’est juste? Eh bien lui c’est pareil, c’est Juste.",
    personage: ["Pierre Brochant", "François Pignon"],
    actor: ["Thierry Lhermitte", "Jacques Villeret"],
    film: "Le dîner de cons",
    year: 1998,
    from: "Francis Veber",
  },
  {
    id: "26",
    quote: "Merci la gueuse. Tu es un laideron mais tu es bien bonne.",
    personage: "Jacquouille",
    actor: "Christian Clavier",
    film: "les Visiteurs",
    year: 1993,
    from: "Jean-Marie Poiré ",
  },

  {
    id: "27",
    quote:
      "Très bien, on va faire l’appel. – Pierre? – Présent. – Pierre? – Présent. – Pierre? – Présente. – Pierre? – Présente. – Ah, Pierre? – Présent. – Pierre? … Pierre… Évidemment encore absent celui-là. J’imagine que Pierre n’est pas là non plus! Comme par hasard, toujours ensemble ces deux-là.",
    personage: "Pierre",
    actor: "Maurice Barthélémy",
    film: "RRRrrrr !!!",
    year: 2004,
    from: "Alain Chabat",
  },
  {
    id: "28",
    quote:
      "Mais je vous en prie. Figurez-vous que Thérèse n’est pas moche. Elle n’a pas un physique facile… C’est différent",
    personage: "Pierre ",
    actor: "Thierry Lhermitte",
    film: "Le père noël est une ordure",
    year: 1982,
    from: "Jean-Marie Poiré",
  },
  /*{
    id: "29",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "30",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "31",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "32",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "33",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "34",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "35",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "36",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "37",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "38",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "39",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "40",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "41",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "42",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "43",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "44",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "45",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "46",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "47",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "48",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "49",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "50",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "51",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "52",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "53",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "54",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "55",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "56",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "57",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "58",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },

  {
    id: "59",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "60",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "61",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "62",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "63",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "64",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "65",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "66",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "67",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "68",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "69",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "70",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "71",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "72",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "73",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },
  {
    id: "74",
    quote: "",
    personage: "",
    actor: "",
    film: "",
    year: 19,
    from: "",
  },*/
];
